name: Node.js CI

# Trigger the workflow on push or pull request to the master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    # Run the job on Ubuntu, macOS, and Windows
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    # Run the job on the matrix OS
    runs-on: ${{ matrix.os }}

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (ensure >= 18.x)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          # Use the latest Node.js version that is >= 18
          node-version: '>=18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Compile TypeScript
      - name: Compile TypeScript
        run: npm run build  # This assumes you have a "build" script in package.json that runs "tsc"

      # Step 5: Run tests with --detectOpenHandles flag
      - name: Run tests
        run: npm test -- --detectOpenHandles
