name: Node.js CI

# Trigger the workflow on push or pull request to the master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '>=18'

      # Set the CI environment variable to true
      - name: Set CI environment variable
        if: runner.os == 'Windows'
        run: |
          echo "CI=true" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install --omit=optional --loglevel verbose
        timeout-minutes: 1

      - name: Compile TypeScript
        run: npm run build

      - name: Run tests
        run: npm test -- --detectOpenHandles
