name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '>=18'

      - name: Set CI environment variable
        run: echo "CI=true" >> $GITHUB_ENV

      # - name: Clear npm cache
      #   run: npm cache clean --force

      - name: Install dependencies
        run: npm ci 
        # timeout-minutes: 10

      - name: Compile TypeScript
        run: npm run build

      - name: Run tests
        run: npm test -- --detectOpenHandles
